project:
  type: book
  output-dir: docs

date: today
date-format: long

from: markdown+emoji

book:
  title: "User Guide: Dark Data"
  author: "Cole Boyer"
  page-footer:
    left: "Copyright 2025, Cole Boyer"
  chapters:
    - index.qmd
    - naniar.qmd
    - survival.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - topic.qmd
    - needs.qmd
    - task-analysis.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt


