
# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup? 
  - Basic knowledge of coding in R, specifically basics on how to view a data set and packages like ggplot2 
  - Recognizing missing values and gaps in the data
  - Knowing the goal you have in mind for what the dark data will accomplish when it is handled

What are the basic requirements for any data that the method is used on? 
  - Are missing values allowed? 
  Missing data is the topic of my user guide
  - Should the data be confined within a certain range?
  Not necessarily
  - Does the data have to be approximately normally distributed? 
  No

What are the basic components of the task?
  - Several options on how to handle dark data will be discussed
  - Missing data:
      - How to spot it and visualize it using ggplot
      - How to view a numeric summary of missing values
  - Censored data:
      - Talk over the survival package and how to deal with censored data
      


What decisions does the user need to be prepared to make on the fly?
The user needs to decide what role the dark data plays in the context of their work. Certain goals will require different strategies of dealing with dark data.

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?
By the end of the user guide, the user should have a better understanding of not only how to handle dark data, but also how to identify types of dark data, since there are different strategies to use for different types of dark data.

## Additional Guidance 

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic). 

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. 
This document should remain as an appendix to your main report. 