# Topic

Pick some subset of the information covered in your annual review article that you are interested in exploring in more detail. 

Identify the scope of your user guide - what will you cover? Specific software packages? When to use or not to use a specific technique?

In my user guide, I would like to dive deeper into "dark data." Dark data is a term that is used to describe data that is lost or distorted before analysis (the most common being missing/incomplete data). In my user guide, I would like to discuss what it is, where we commonly see it in real life, and how statisticians deal with it to get the results they are looking for. As far as packages to discuss, I will most likely cover packages such like tidyr, stringr, and lubridate in R. For the packages that I end up discussing, I will also discuss when and when not to use them.



::: callout-note
# Dr. V's comments

Look into `naniar`. I don't think it's useful to discuss the tidyverse that much - it's pretty common - but it is probably good to look for specific R packages and approaches that focus on missing/incomplete data evaluations. I would also see if you can find anything that talks about missing at random vs. missing not at random and how to evaluate that. Additionally, censored data that can't be measured above/below a certain value is common, and there are packages to help deal with that as well -- see if your annual review article mentions any. 

:::